version: "3.7"
services:
    # Imagem do projeto
    laravel_8:
        build:
            args:
                user: nelsonp2n
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/ # working dir
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - queue
        networks:
            - my_network
    
    # Nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - my_network

    # Mysql
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3388:3306
        networks:
            - my_network

    # Queue
    queue:
        build:
            args:
                user: nelsonp2n
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - my_network
    
    # Redis
    redis:
        image: redis:latest
        networks:
            - my_network

networks:
    my_network:
        driver: bridge